### ISSUE TITLE
[Feature] Short description of your request

### ISSUE THREAD

**Issue by HenShalom** [brizzai/auto-mcp#13]
### What feature would you like to see?
**Full OAuth passthrough** – Auto-MCP should proxy the entire OAuth lifecycle (well-known discovery endpoints, token exchange, callback, etc.) to the upstream backend without altering headers or bodies.

### Why is this feature useful?
* Lets clients complete OAuth flows through Auto-MCP exactly as if they were talking to the backend directly.
* Keeps Auto-MCP stateless and IDP-agnostic (no secret or token storage).
* Extends Issue #11 - for both using mcp as oAuth server or as a proxy 

### Additional context (optional)
```yaml
oauth_passthrough:
  enabled: true
  base_path: "/oauth"               # root for authorize, token, register, callback
  well_known:
    - "/.well-known/oauth-protected-resource"
    - "/.well-known/oauth-authorization-server"
  auth_header_type: "bearer" # what header the backend except the auth 
```
